### ISSUE TITLE
Do you have a suggestion for a place to host the killbot? 

### ISSUE THREAD

**Issue by HansHovanitz** [bearlikelion/ao-killbot#2]
I was wondering if you had any suggestions on a good place to host this killbot? I got it running on my local fine (and it's awesome!) but I don't want to leave my computer running 24/7. 

Also, how often does the killbot poll/update to search for new kills/deaths?

Thanks!

**Comment by bearlikelion** [comment]
A lot of people have been using the free tier of Heroku
https://www.heroku.com/

By default the bot checks every 30s, you can modify the timer interval to set a custom time:
https://github.com/bearlikelion/ao-killbot/blob/master/ao-killboard.js#L172

**Comment by HansHovanitz** [comment]
Hey, thanks much for the reply. Yeah I just looked through the code and saw the time timer. I'll close this now. Thanks again!
